### PR TITLE
New design fix warnings

### LINKED ISSUE #1131: Warnings are anoying (new design).
### 📝 Summary

`pnpm check` gives like 30 warning. This is annoying when you want to find *your* warnings.

### 📍 Affected area(s)

development

### ✅ Expected behavior

no warnings

### ❌ Actual behavior

`svelte-check found 0 errors and 31 warnings in 7 files`

### 🔁 Reproduction steps

1. `git checkout new-design`
2. `pnpm check`

### 🌍 Scope & impact

- developers
- CPU volunteers
- Aspiring volunteers
- Other contributors

### 🛠️ Technical notes

_No response_

### ❓ Next steps/open questions

_No response_

### PR DESCRIPTION
**Pull request by SLUCHABLUB**
### 🧩 Summary

Remove the warnings.

### 🔗 Related issues (if any)

Closes #1131 

### 📸 Screenshots / recordings (if applicable)

Befor:
Screenshot from 2026-03-22 20-40-47
After:
Screenshot from 2026-03-22 20-38-31

### CODE REVIEW

File: src/routes/(app)/news/create/+page.svelte [hunk 1]
```diff
@@ -12,6 +12,7 @@
 
   let { data }: { data: PageData } = $props();
 
+  // svelte-ignore state_referenced_locally
```
Comment (memagu) [inline src/routes/(app)/news/create/+page.svelte]: Perhaps it would be cleaner to use svelte's `untrack` on `data.form` instead of ignoring the warning.

Replace `data.form` with `untrack(() => data.form)` and add `import { untrack } from 'svelte';` to imports.

**Review by memagu — CHANGES_REQUESTED** [review]
Lgtm for the most part, well done! See comments :D

It's gonna be so nice to have the warnings out of the way!!

**Review by Tomas-Ka — APPROVED** [review]
looks good!
